// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJI8QW7tXyhA9VXX3neNBNdHshMOisAaE',
    appId: '1:912160118580:web:546cd6f96778e6f7aaf761',
    messagingSenderId: '912160118580',
    projectId: 'dentalflow-8590e',
    authDomain: 'dentalflow-8590e.firebaseapp.com',
    storageBucket: 'dentalflow-8590e.firebasestorage.app',
    measurementId: 'G-1TDDP07QJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAm7OISys8w7tRDErKl7h9QZ13izwpKEU',
    appId: '1:912160118580:android:226106a60cca0964aaf761',
    messagingSenderId: '912160118580',
    projectId: 'dentalflow-8590e',
    storageBucket: 'dentalflow-8590e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOIITGDwohCggkOW1YZNAqwT-RqUM34Y8',
    appId: '1:912160118580:ios:cc376d8b164aeb70aaf761',
    messagingSenderId: '912160118580',
    projectId: 'dentalflow-8590e',
    storageBucket: 'dentalflow-8590e.firebasestorage.app',
    iosBundleId: 'com.example.dentalflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOIITGDwohCggkOW1YZNAqwT-RqUM34Y8',
    appId: '1:912160118580:ios:cc376d8b164aeb70aaf761',
    messagingSenderId: '912160118580',
    projectId: 'dentalflow-8590e',
    storageBucket: 'dentalflow-8590e.firebasestorage.app',
    iosBundleId: 'com.example.dentalflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJI8QW7tXyhA9VXX3neNBNdHshMOisAaE',
    appId: '1:912160118580:web:f4510e06caf5e9ceaaf761',
    messagingSenderId: '912160118580',
    projectId: 'dentalflow-8590e',
    authDomain: 'dentalflow-8590e.firebaseapp.com',
    storageBucket: 'dentalflow-8590e.firebasestorage.app',
    measurementId: 'G-RN2CFSXFC2',
  );
}
